apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/jenkins-integrator:latest
          ports:
            - containerPort: 3000
          env:
            - name: DOCKER_ENV
              value: "dev"