apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
#         uncomment and update with Java image
#           image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/jenkins-integrator:v10
#         OR uncomment and update with python image
#           image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/argo-demo:latest
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/python-example:v1
          ports:
            - containerPort: 5000
          env:
          - name: DOCKER_ENV
            value: "dev"
