apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-demo
    env: dev
    tier: backend
  name: argo-demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: kafka-integrator
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/kafka-integrator:latest
          ports:
            - containerPort: 3000
          env:
            - name: spring.profiles.active
              value: dev
